services:
  app:
    build:
      context: .
      dockerfile: docker/franken.Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=silentdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=xcWI3128
      - QUEUE_CONNECTION=rabbitmq
    depends_on:
      - rabbitmq
      - redis
    ports:
      - 8090:80
    command: ["frankenphp", "-c", "/etc/frankenphp.yaml"]

  rabbitmq:
    image: rabbitmq:4.0.4-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "127.0.0.1:9003:9000"
      - "127.0.0.1:9004:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  db_data:
    driver: local
  media:
  minio_data:
    driver: local
